CREATE TABLE tbl_users (
  user_id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  first_name VARCHAR(50) NOT NULL,
  last__name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON tbl_users(email);